import { LocalizationRow, Namespace } from "./types";

export const data: LocalizationRow[] = [
  // Digital Whiteboard (DWB prefix)
  {
    id: "1",
    phraseKey: "DWB_WelcomeMessage",
    defaultTranslation: "Welcome to the Whiteboard",
    description: "Greeting message displayed when entering the whiteboard",
    screenshot: "https://placehold.co/100x100",
    translations: {
      //   fr: "Bienvenue au tableau blanc",
      fr: "",
      de: "Willkommen beim Whiteboard",
      es: "Bienvenido al tablero blanco",
    },
    namespace: "Digital Whiteboard",
  },
  {
    id: "2",
    phraseKey: "DWB_SaveDrawing",
    defaultTranslation: "Save Drawing",
    description: "Button label for saving the drawing",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Enregistrer le dessin",
      de: "Zeichnung speichern",
      es: "Guardar dibujo",
    },
    namespace: "Digital Whiteboard",
  },
  {
    id: "3",
    phraseKey: "DWB_ClearBoard",
    defaultTranslation: "Clear Board",
    description: "Button label for clearing the whiteboard",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Effacer le tableau",
      de: "Tafel löschen",
      es: "Limpiar tablero",
    },
    namespace: "Digital Whiteboard",
  },
  {
    id: "4",
    phraseKey: "DWB_UndoAction",
    defaultTranslation: "Undo",
    description: "Button label for undoing the last action",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Annuler",
      de: "Rückgängig",
      es: "Deshacer",
    },
    namespace: "Digital Whiteboard",
  },
  {
    id: "5",
    phraseKey: "DWB_RedoAction",
    defaultTranslation: "Redo",
    description: "Button label for redoing the last undone action",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Refaire",
      de: "Wiederherstellen",
      es: "Rehacer",
    },
    namespace: "Digital Whiteboard",
  },
  {
    id: "6",
    phraseKey: "DWB_AddStickyNote",
    defaultTranslation: "Add Sticky Note",
    description: "Button label for adding a sticky note",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Ajouter un post-it",
      de: "Notizzettel hinzufügen",
      es: "Agregar nota adhesiva",
    },
    namespace: "Digital Whiteboard",
  },
  {
    id: "7",
    phraseKey: "DWB_ZoomIn",
    defaultTranslation: "Zoom In",
    description: "Button label for zooming in on the whiteboard",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Agrandir",
      de: "Vergrößern",
      es: "Acercar",
    },
    namespace: "Digital Whiteboard",
  },
  {
    id: "8",
    phraseKey: "DWB_ZoomOut",
    defaultTranslation: "Zoom Out",
    description: "Button label for zooming out on the whiteboard",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Rétrécir",
      de: "Verkleinern",
      es: "Alejar",
    },
    namespace: "Digital Whiteboard",
  },
  {
    id: "9",
    phraseKey: "DWB_ShareWhiteboard",
    defaultTranslation: "Share Whiteboard",
    description: "Button label for sharing the whiteboard",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Partager le tableau blanc",
      de: "Whiteboard teilen",
      es: "Compartir pizarra",
    },
    namespace: "Digital Whiteboard",
  },
  {
    id: "10",
    phraseKey: "DWB_ExportDrawing",
    defaultTranslation: "Export Drawing",
    description: "Button label for exporting the current drawing",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Exporter le dessin",
      de: "Zeichnung exportieren",
      es: "Exportar dibujo",
    },
    namespace: "Digital Whiteboard",
  },

  // My Stay Mobile (BYOD prefix)
  {
    id: "11",
    phraseKey: "BYOD_WelcomeMessage",
    defaultTranslation: "Welcome to My Stay Mobile",
    description: "Greeting message when entering the app",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Bienvenue dans Mon Séjour Mobile",
      de: "Willkommen bei My Stay Mobile",
      es: "Bienvenido a Mi Estancia Móvil",
    },
    namespace: "My Stay Mobile",
  },
  {
    id: "12",
    phraseKey: "BYOD_LoginButton",
    defaultTranslation: "Login",
    description: "Text displayed on the login button",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Connexion",
      de: "Anmeldung",
      es: "Iniciar sesión",
    },
    namespace: "My Stay Mobile",
  },
  {
    id: "13",
    phraseKey: "BYOD_HelpSection",
    defaultTranslation: "Help",
    description: "Section label for help topics",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Aide",
      de: "Hilfe",
      es: "Ayuda",
    },
    namespace: "My Stay Mobile",
  },
  {
    id: "14",
    phraseKey: "BYOD_CheckoutButton",
    defaultTranslation: "Checkout",
    description: "Button text for completing the checkout process",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Commander",
      de: "Zur Kasse",
      es: "Realizar pedido",
    },
    namespace: "My Stay Mobile",
  },
  {
    id: "15",
    phraseKey: "BYOD_ReservationPage",
    defaultTranslation: "Reservations",
    description: "Page label for reservations",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Réservations",
      de: "Reservierungen",
      es: "Reservas",
    },
    namespace: "My Stay Mobile",
  },
  {
    id: "16",
    phraseKey: "BYOD_ContactUs",
    defaultTranslation: "Contact Us",
    description: "Link for contacting customer support",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Nous contacter",
      de: "Kontaktieren Sie uns",
      es: "Contáctenos",
    },
    namespace: "My Stay Mobile",
  },
  {
    id: "17",
    phraseKey: "BYOD_LanguageSelection",
    defaultTranslation: "Select Language",
    description: "Dropdown label for selecting language",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Choisir la langue",
      de: "Sprache auswählen",
      es: "Seleccionar idioma",
    },
    namespace: "My Stay Mobile",
  },
  {
    id: "18",
    phraseKey: "BYOD_OrderHistory",
    defaultTranslation: "Order History",
    description: "Label for order history page",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Historique des commandes",
      de: "Bestellverlauf",
      es: "Historial de pedidos",
    },
    namespace: "My Stay Mobile",
  },
  {
    id: "19",
    phraseKey: "BYOD_PaymentMethod",
    defaultTranslation: "Payment Method",
    description: "Label for selecting payment methods",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Méthode de paiement",
      de: "Zahlungsmethode",
      es: "Método de pago",
    },
    namespace: "My Stay Mobile",
  },
  {
    id: "20",
    phraseKey: "BYOD_PushNotifications",
    defaultTranslation: "Enable Push Notifications",
    description: "Button label for enabling push notifications",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Activer les notifications push",
      de: "Push-Benachrichtigungen aktivieren",
      es: "Habilitar notificaciones push",
    },
    namespace: "My Stay Mobile",
  },

  // Xamarin Client (No prefix)
  {
    id: "21",
    phraseKey: "SettingsPage",
    defaultTranslation: "Settings",
    description: "Navigation label for the settings page",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Paramètres",
      de: "Einstellungen",
      es: "Configuraciones",
    },
    namespace: "Xamarin Client",
  },
  {
    id: "22",
    phraseKey: "ProfilePage",
    defaultTranslation: "Profile",
    description: "Label for the user profile page",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Profil",
      de: "Profil",
      es: "Perfil",
    },
    namespace: "Xamarin Client",
  },
  {
    id: "23",
    phraseKey: "LoginErrorMessage",
    defaultTranslation: "Invalid username or password",
    description: "Error message displayed for invalid login credentials",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Nom d'utilisateur ou mot de passe invalide",
      de: "Ungültiger Benutzername oder Passwort",
      es: "Nombre de usuario o contraseña inválido",
    },
    namespace: "Xamarin Client",
  },
  {
    id: "24",
    phraseKey: "LogoutButton",
    defaultTranslation: "Logout",
    description: "Button text for logging out",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Déconnexion",
      de: "Abmelden",
      es: "Cerrar sesión",
    },
    namespace: "Xamarin Client",
  },
  {
    id: "25",
    phraseKey: "TermsOfServiceLink",
    defaultTranslation: "Terms of Service",
    description: "Link to terms of service",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Conditions d'utilisation",
      de: "Nutzungsbedingungen",
      es: "Términos de servicio",
    },
    namespace: "Xamarin Client",
  },
  {
    id: "26",
    phraseKey: "PrivacyPolicyLink",
    defaultTranslation: "Privacy Policy",
    description: "Link to privacy policy",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Politique de confidentialité",
      de: "Datenschutzrichtlinie",
      es: "Política de privacidad",
    },
    namespace: "Xamarin Client",
  },
  {
    id: "27",
    phraseKey: "SubmitButton",
    defaultTranslation: "Submit",
    description: "Button text for submitting forms",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Soumettre",
      de: "Einreichen",
      es: "Enviar",
    },
    namespace: "Xamarin Client",
  },
  {
    id: "28",
    phraseKey: "CancelButton",
    defaultTranslation: "Cancel",
    description: "Button text for cancelling actions",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Annuler",
      de: "Abbrechen",
      es: "Cancelar",
    },
    namespace: "Xamarin Client",
  },
  {
    id: "29",
    phraseKey: "DeleteAccountButton",
    defaultTranslation: "Delete Account",
    description: "Button text for deleting the user account",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Supprimer le compte",
      de: "Konto löschen",
      es: "Eliminar cuenta",
    },
    namespace: "Xamarin Client",
  },
  {
    id: "30",
    phraseKey: "SearchPlaceholder",
    defaultTranslation: "Search...",
    description: "Placeholder text for the search input",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Rechercher...",
      de: "Suche...",
      es: "Buscar...",
    },
    namespace: "Xamarin Client",
  },

  // React Client
  {
    id: "31",
    phraseKey: "RC_Welcome",
    defaultTranslation: "Welcome to React",
    description: "Welcome message for React client users",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Bienvenue dans React",
      de: "Willkommen bei React",
      es: "Bienvenido a React",
    },
    namespace: "React Client",
  },
  {
    id: "32",
    phraseKey: "RC_Settings",
    defaultTranslation: "Settings",
    description: "Label for the settings page",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Paramètres",
      de: "Einstellungen",
      es: "Configuraciones",
    },
    namespace: "React Client",
  },
  {
    id: "33",
    phraseKey: "RC_Logout",
    defaultTranslation: "Logout",
    description: "Label for the logout button",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Déconnexion",
      de: "Abmelden",
      es: "Cerrar sesión",
    },
    namespace: "React Client",
  },
  {
    id: "34",
    phraseKey: "RC_Save",
    defaultTranslation: "Save",
    description: "Label for save button",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Enregistrer",
      de: "Speichern",
      es: "Guardar",
    },
    namespace: "React Client",
  },
  {
    id: "35",
    phraseKey: "RC_Submit",
    defaultTranslation: "Submit",
    description: "Button label for submitting forms",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Soumettre",
      de: "Einreichen",
      es: "Enviar",
    },
    namespace: "React Client",
  },
  {
    id: "36",
    phraseKey: "RC_Profile",
    defaultTranslation: "Profile",
    description: "Label for the profile section",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Profil",
      de: "Profil",
      es: "Perfil",
    },
    namespace: "React Client",
  },
  {
    id: "37",
    phraseKey: "RC_Language",
    defaultTranslation: "Language",
    description: "Label for selecting languages",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Langue",
      de: "Sprache",
      es: "Idioma",
    },
    namespace: "React Client",
  },
  {
    id: "38",
    phraseKey: "RC_Search",
    defaultTranslation: "Search",
    description: "Search input placeholder",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Rechercher",
      de: "Suche",
      es: "Buscar",
    },
    namespace: "React Client",
  },
  {
    id: "39",
    phraseKey: "RC_Notifications",
    defaultTranslation: "Notifications",
    description: "Label for notifications section",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Notifications",
      de: "Benachrichtigungen",
      es: "Notificaciones",
    },
    namespace: "React Client",
  },
  {
    id: "40",
    phraseKey: "RC_Help",
    defaultTranslation: "Help",
    description: "Label for the help section",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Aide",
      de: "Hilfe",
      es: "Ayuda",
    },
    namespace: "React Client",
  },

  // Digital Door Sign
  {
    id: "41",
    phraseKey: "DDS_WelcomeMessage",
    defaultTranslation: "Welcome",
    description: "Message shown on the digital door sign",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Bienvenue",
      de: "Willkommen",
      es: "Bienvenido",
    },
    namespace: "Digital Door Sign",
  },
  {
    id: "42",
    phraseKey: "DDS_ExitMessage",
    defaultTranslation: "Exit",
    description: "Message shown when leaving the building",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Sortie",
      de: "Ausgang",
      es: "Salida",
    },
    namespace: "Digital Door Sign",
  },
  {
    id: "43",
    phraseKey: "DDS_RoomOccupied",
    defaultTranslation: "Room Occupied",
    description: "Message indicating that the room is occupied",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Salle occupée",
      de: "Zimmer besetzt",
      es: "Habitación ocupada",
    },
    namespace: "Digital Door Sign",
  },
  {
    id: "44",
    phraseKey: "DDS_RoomAvailable",
    defaultTranslation: "Room Available",
    description: "Message indicating that the room is available",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Salle disponible",
      de: "Zimmer verfügbar",
      es: "Habitación disponible",
    },
    namespace: "Digital Door Sign",
  },
  {
    id: "45",
    phraseKey: "DDS_CleaningInProgress",
    defaultTranslation: "Cleaning in Progress",
    description: "Message indicating that cleaning is in progress",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Nettoyage en cours",
      de: "Reinigung im Gange",
      es: "Limpieza en progreso",
    },
    namespace: "Digital Door Sign",
  },
  {
    id: "46",
    phraseKey: "DDS_ConferenceMode",
    defaultTranslation: "Conference Mode",
    description: "Message indicating that the room is in conference mode",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Mode conférence",
      de: "Konferenzmodus",
      es: "Modo conferencia",
    },
    namespace: "Digital Door Sign",
  },
  {
    id: "47",
    phraseKey: "DDS_MeetingScheduled",
    defaultTranslation: "Meeting Scheduled",
    description: "Message indicating that a meeting is scheduled",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Réunion programmée",
      de: "Meeting geplant",
      es: "Reunión programada",
    },
    namespace: "Digital Door Sign",
  },
  {
    id: "48",
    phraseKey: "DDS_MeetingInProgress",
    defaultTranslation: "Meeting in Progress",
    description: "Message indicating that a meeting is in progress",
    screenshot: "https://placehold.co/100x100",
    translations: {
      //   fr: "Réunion en cours",
      fr: "",
      de: "Besprechung im Gange",
      es: "Reunión en curso",
    },
    namespace: "Digital Door Sign",
  },
  {
    id: "49",
    phraseKey: "DDS_TakeABreak",
    defaultTranslation: "Take a Break",
    description: "Message encouraging people to take a break",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Prenez une pause",
      //   de: "Machen Sie eine Pause",
      de: "",
      es: "Tómate un descanso",
    },
    namespace: "Digital Door Sign",
  },
  {
    id: "50",
    phraseKey: "DDS_NoEntry",
    defaultTranslation: "No Entry",
    description: "Message indicating restricted entry",
    screenshot: "https://placehold.co/100x100",
    translations: {
      fr: "Entrée interdite",
      de: "Kein Eintritt",
      //   es: "No entrada",
      es: "",
    },
    namespace: "Digital Door Sign",
  },
];

export const namespaces: Namespace[] = [
  "React Client",
  "Xamarin Client",
  "Digital Door Sign",
  "Digital Whiteboard",
  "My Stay Mobile",
];

export const languages = [
  { code: "fr", name: "French" },
  { code: "de", name: "German" },
  { code: "es", name: "Spanish" },
];
